### PR TITLE
Create barebones testing/data files

### PR DESCRIPTION
**Pull request by joel-becker**
First pull request!

### CODE REVIEW

**Comment by EdJeeOnGitHub** [comment]
Thanks Joel! ♥️

Can you revert the commit that deletes .Rbuildignore etc.?

We actually need buildignore for the package, I'm not sure about the others.

I can edit this evening if you don't get the chance.

**Comment by joel-becker** [comment]
Reverted to the one previously by accident, but that's good enough...

What kind of things do you intend to put in `.Rbuildignore`?

**Comment by EdJeeOnGitHub** [comment]
Hmmm I think reverting the commit before will still delete our .Rbuildignore file. I'll check properly this evening though

**Comment by EdJeeOnGitHub** [comment]
I've added tests and data from the authors so just going to close this @joel-becker  


RIP PR; it's the thought that counts.

We'll get 'em next time.

**Pull request closed without merging**
